# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/xmjyever/clion-2020.3.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/xmjyever/clion-2020.3.1/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xmjyever/CLionProjects/MyTinyServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xmjyever/CLionProjects/MyTinyServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/xmjyever/clion-2020.3.1/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/xmjyever/clion-2020.3.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xmjyever/CLionProjects/MyTinyServer/CMakeFiles /home/xmjyever/CLionProjects/MyTinyServer/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xmjyever/CLionProjects/MyTinyServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyTinyServer

# Build rule for target.
MyTinyServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyTinyServer
.PHONY : MyTinyServer

# fast build rule for target.
MyTinyServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTinyServer.dir/build.make CMakeFiles/MyTinyServer.dir/build
.PHONY : MyTinyServer/fast

http_conn.o: http_conn.cpp.o

.PHONY : http_conn.o

# target to build an object file
http_conn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTinyServer.dir/build.make CMakeFiles/MyTinyServer.dir/http_conn.cpp.o
.PHONY : http_conn.cpp.o

http_conn.i: http_conn.cpp.i

.PHONY : http_conn.i

# target to preprocess a source file
http_conn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTinyServer.dir/build.make CMakeFiles/MyTinyServer.dir/http_conn.cpp.i
.PHONY : http_conn.cpp.i

http_conn.s: http_conn.cpp.s

.PHONY : http_conn.s

# target to generate assembly for a file
http_conn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTinyServer.dir/build.make CMakeFiles/MyTinyServer.dir/http_conn.cpp.s
.PHONY : http_conn.cpp.s

processpool/processpool_server.o: processpool/processpool_server.cpp.o

.PHONY : processpool/processpool_server.o

# target to build an object file
processpool/processpool_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTinyServer.dir/build.make CMakeFiles/MyTinyServer.dir/processpool/processpool_server.cpp.o
.PHONY : processpool/processpool_server.cpp.o

processpool/processpool_server.i: processpool/processpool_server.cpp.i

.PHONY : processpool/processpool_server.i

# target to preprocess a source file
processpool/processpool_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTinyServer.dir/build.make CMakeFiles/MyTinyServer.dir/processpool/processpool_server.cpp.i
.PHONY : processpool/processpool_server.cpp.i

processpool/processpool_server.s: processpool/processpool_server.cpp.s

.PHONY : processpool/processpool_server.s

# target to generate assembly for a file
processpool/processpool_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTinyServer.dir/build.make CMakeFiles/MyTinyServer.dir/processpool/processpool_server.cpp.s
.PHONY : processpool/processpool_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MyTinyServer"
	@echo "... http_conn.o"
	@echo "... http_conn.i"
	@echo "... http_conn.s"
	@echo "... processpool/processpool_server.o"
	@echo "... processpool/processpool_server.i"
	@echo "... processpool/processpool_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

